on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Creating Docker image
    steps:
    - name: Hello world action step
      id: hello
      uses: hiitsalex/ecommerce/.github/actions@v3
      with:
        who-to-greet: 'Everyone'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"

 
  build:
    name: Build project
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm ci
    - run: npm run build --if-present


  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
          repository: hiitsalex/ecommerce
          tag_with_ref: true
    